apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: mike@mikeroysoft.com
    privateKeySecretRef:
      name: mrs-www-stage-certificates
    # Enable the HTTP-01 challenge provider
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: contour