version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
         name: Login to the Docker Registry
         command: docker login --username $DOCKER_USER --password=$DOCKER_PASS
      - run:
          name: Build the Docker Image
          command: docker build -t $DOCKER_IMAGE:$CIRCLE_TAG .
      - deploy:
          name: Push the Docker Image
          command: docker push $DOCKER_IMAGE:$CIRCLE_TAG