# config.yml for CircleCI
# This puppy will build our container using a standard docker:stable-git container
# It will tag the build with the git tag applied ($CIRCLE_TAG)
# Once built it will push the image to docker hub
#
# To do: Deploy this image with Helm
# Branches:
# - Master
# - Stable
# - 'versioned' (v0.1.3)
# Open Question: how do I get the same docker image built for branch and image at the same time? Shouldn't this 'just do it'?
# Answer: It does it, but it fails because the commit that triggers the build doesn't include the tag.
# Once you, after the commit, push the tag, a build is triggered in Circle

# This is _MASTER_ branch
# My man...
# one more try...

version: 2
jobs:
  # Create a job to build our Hugo site using Docker and push the resulting docker image up to
  # our configured Docker registry (Docker Hub).
  build_tag:
    docker:
      # Since Circle CI needs to be able to clone our repository from GitHub, BitBucket, etc,
      # we need to use a docker image that has the git binary installed
      - image: docker:stable-git
    steps:
      - checkout
      
      # Pull the submodules
      # right now it's just the theme, but let's add the content here later on
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

 # setting up the remote Docker 
      - setup_remote_docker
      - run:
          name: Login to the Docker Registry
          command: echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: What is CIRCLE_TAG ?
          command: echo $CIRCLE_TAG    
      - run:
          name: Build the Docker Image
          command: docker build -t $DOCKER_IMAGE:$CIRCLE_TAG .
      - run:
          name: Push the Docker Image
          command: docker push $DOCKER_IMAGE:$CIRCLE_TAG
      - run:
          name: What is CIRCLE_TAG ?
          command: echo $CIRCLE_TAG    

  build_branch:
    docker:
      # Since Circle CI needs to be able to clone our repository from GitHub, BitBucket, etc,
      # we need to use a docker image that has the git binary installed
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to the Docker Registry
          command: echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Build the Docker Image
          command: docker build -t $DOCKER_IMAGE:$CIRCLE_BRANCH .
      - run:
          name: Push the Docker Image
          command: docker push $DOCKER_IMAGE:$CIRCLE_BRANCH

workflows:
  version: 2
  build_tag_and_build_branch:
    jobs:
      - build_tag:
          filters:
            tags:
              only: /^v.*/
      - build_branch