version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}} 
    steps:
      - checkout
      - setup_remote_docker
      - run:
         name: Login to the Docker Registry
         command: docker login --username $DOCKER_USER --password=$DOCKER_PASS
      - run:
          name: Build the Docker Image
          command: docker build -t $DOCKER_IMAGE:$CIRCLE_TAG .
      - run:
          name: Push the Docker Image
          command: docker push $DOCKER_IMAGE:$CIRCLE_TAG