# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# MASTER BRANCH


replicaCount: 3

image:
  repository: mikeroysoft/mrs-hugo
  tag: stable
  pullPolicy: Always

imagePullSecrets: 
  - name: mrs-regcred

nameOverride: "mrs-www-prod"
fullnameOverride: "mrs-www-prod"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  path: /
  hosts: 
    - mikeroysoft.com

  
  annotations: 
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
 
  tls:
     - secretName: letsencrypt-prod
       hosts:
         - mikeroysoft.com


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
