apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mrs-www-dev
  name: mrs-www-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mrs-www-dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mrs-www-dev
    spec:
      containers:
      - image: docker.io/mikeroysoft/mrs-hugo:dev
        name: mrs-www-dev
        ports:
        - containerPort: 80
          name: http
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30    
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mrs-www-dev
  name: mrs-www-dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mrs-www-dev
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1  
kind: Ingress
metadata:
  name: mrs-www-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
  labels:
    app: mrs-www-dev
spec:
  rules:
  - host: "dev.mikeroysoft.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mrs-www-dev
            port:
              number: 80
  tls:
  - hosts:
    - dev.mikeroysoft.com
    secretName: mrs-www-dev            